export const countriesES = [
  { code: "AFG", country: "Afganistán" },
  { code: "ALB", country: "Albania" },
  { code: "DZA", country: "Argelia" },
  { code: "ASM", country: "Samoa Americana" },
  { code: "AND", country: "Andorra" },
  { code: "AGO", country: "Angola" },
  { code: "AIA", country: "Anguila" },
  { code: "ATA", country: "Antártida" },
  { code: "ATG", country: "Antigua y Barbuda" },
  { code: "ARG", country: "Argentina" },
  { code: "ARM", country: "Armenia" },
  { code: "ABW", country: "Aruba" },
  { code: "AUS", country: "Australia" },
  { code: "AUT", country: "Austria" },
  { code: "AZE", country: "Azerbaiyán" },
  { code: "BHS", country: "Bahamas" },
  { code: "BHR", country: "Bahrein" },
  { code: "BGD", country: "Bangladesh" },
  { code: "BRB", country: "Barbados" },
  { code: "BLR", country: "Bielorrusia" },
  { code: "BEL", country: "Bélgica" },
  { code: "BLZ", country: "Belice" },
  { code: "BEN", country: "Benin" },
  { code: "BMU", country: "Bermudas" },
  { code: "BTN", country: "Bután" },
  { code: "BOL", country: "Bolivia" },
  { code: "BIH", country: "Bosnia y Herzegovina" },
  { code: "BWA", country: "Botswana" },
  { code: "BVT", country: "Isla Bouvet" },
  { code: "BRA", country: "Brasil" },
  { code: "IOT", country: "Territorio Británico del Océano Índico" },
  { code: "BRN", country: "Brunei Darussalam" },
  { code: "BGR", country: "Bulgaria" },
  { code: "BFA", country: "Burkina Faso" },
  { code: "BDI", country: "Burundi" },
  { code: "KHM", country: "Camboya" },
  { code: "CMR", country: "Camerún" },
  { code: "CAN", country: "Canadá" },
  { code: "CPV", country: "Cabo Verde" },
  { code: "CYM", country: "Islas Caimán" },
  { code: "CAF", country: "República Centroafricana" },
  { code: "TCD", country: "Chad" },
  { code: "CHL", country: "Chile" },
  { code: "CHN", country: "China" },
  { code: "CXR", country: "Isla de Navidad" },
  { code: "CCK", country: "Islas Cocos (Keeling)" },
  { code: "COL", country: "Colombia" },
  { code: "COM", country: "Comoras" },
  { code: "COG", country: "Congo" },
  { code: "COD", country: "Congo (República Democrática del)" },
  { code: "COK", country: "Islas Cook" },
  { code: "CRI", country: "Costa Rica" },
  { code: "CIV", country: "Costa de Marfil" },
  { code: "HRV", country: "Croacia" },
  { code: "CUB", country: "Cuba" },
  { code: "CYP", country: "Chipre" },
  { code: "CZE", country: "República Checa" },
  { code: "DNK", country: "Dinamarca" },
  { code: "DJI", country: "Yibuti" },
  { code: "DMA", country: "Dominica" },
  { code: "DOM", country: "República Dominicana" },
  { code: "ECU", country: "Ecuador" },
  { code: "EGY", country: "Egipto" },
  { code: "SLV", country: "El Salvador" },
  { code: "GNQ", country: "Guinea Ecuatorial" },
  { code: "ERI", country: "Eritrea" },
  { code: "EST", country: "Estonia" },
  { code: "ETH", country: "Etiopía" },
  { code: "FLK", country: "Islas Malvinas" },
  { code: "FRO", country: "Islas Feroe" },
  { code: "FJI", country: "Fiji" },
  { code: "FIN", country: "Finlandia" },
  { code: "FRA", country: "Francia" },
  { code: "GUF", country: "Guayana Francesa" },
  { code: "PYF", country: "Polinesia Francesa" },
  { code: "ATF", country: "Tierras Australes Francesas" },
  { code: "GAB", country: "Gabón" },
  { code: "GMB", country: "Gambia" },
  { code: "GEO", country: "Georgia" },
  { code: "DEU", country: "Alemania" },
  { code: "GHA", country: "Ghana" },
  { code: "GIB", country: "Gibraltar" },
  { code: "GRC", country: "Grecia" },
  { code: "GRL", country: "Groenlandia" },
  { code: "GRD", country: "Granada" },
  { code: "GLP", country: "Guadalupe" },
  { code: "GUM", country: "Guam" },
  { code: "GTM", country: "Guatemala" },
  { code: "GIN", country: "Guinea" },
  { code: "GNB", country: "Guinea Bissau" },
  { code: "GUY", country: "Guyana" },
  { code: "HTI", country: "Haití" },
  { code: "HMD", country: "Heard e Islas McDonald" },
  { code: "VAT", country: "Santa Sede" },
  { code: "HND", country: "Honduras" },
  { code: "HKG", country: "Hong Kong" },
  { code: "HUN", country: "Hungría" },
  { code: "ISL", country: "Islandia" },
  { code: "IND", country: "India" },
  { code: "IDN", country: "Indonesia" },
  { code: "IRN", country: "Irán" },
  { code: "IRQ", country: "Iraq" },
  { code: "IRL", country: "Irlanda" },
  { code: "ISR", country: "Israel" },
  { code: "ITA", country: "Italia" },
  { code: "JAM", country: "Jamaica" },
  { code: "JPN", country: "Japón" },
  { code: "JOR", country: "Jordania" },
  { code: "KAZ", country: "Kazajistán" },
  { code: "KEN", country: "Kenia" },
  { code: "KIR", country: "Kiribati" },
  { code: "PRK", country: "República Popular Democrática de Corea" },
  { code: "KOR", country: "República de Corea" },
  { code: "KWT", country: "Kuwait" },
  { code: "KGZ", country: "Kirguistán" },
  { code: "LAO", country: "República Democrática Popular de Lao" },
  { code: "LVA", country: "Letonia" },
  { code: "LBN", country: "Líbano" },
  { code: "LSO", country: "Lesoto" },
  { code: "LBR", country: "Liberia" },
  { code: "LBY", country: "Libia" },
  { code: "LIE", country: "Liechtenstein" },
  { code: "LTU", country: "Lituania" },
  { code: "LUX", country: "Luxemburgo" },
  { code: "MAC", country: "Macao" },
  { code: "MKD", country: "Macedonia del Norte" },
  { code: "MDG", country: "Madagascar" },
  { code: "MWI", country: "Malaui" },
  { code: "MYS", country: "Malasia" },
  { code: "MDV", country: "Maldivas" },
  { code: "MLI", country: "Malí" },
  { code: "MLT", country: "Malta" },
  { code: "MHL", country: "Islas Marshall" },
  { code: "MTQ", country: "Martinica" },
  { code: "MRT", country: "Mauritania" },
  { code: "MUS", country: "Mauricio" },
  { code: "MYT", country: "Mayotte" },
  { code: "MEX", country: "México" },
  { code: "FSM", country: "Micronesia" },
  { code: "MDA", country: "Moldavia" },
  { code: "MCO", country: "Mónaco" },
  { code: "MNG", country: "Mongolia" },
  { code: "MSR", country: "Montserrat" },
  { code: "MAR", country: "Marruecos" },
  { code: "MOZ", country: "Mozambique" },
  { code: "MMR", country: "Myanmar" },
  { code: "NAM", country: "Namibia" },
  { code: "NRU", country: "Nauru" },
  { code: "NPL", country: "Nepal" },
  { code: "NLD", country: "Países Bajos" },
  { code: "NCL", country: "Nueva Caledonia" },
  { code: "NZL", country: "Nueva Zelanda" },
  { code: "NIC", country: "Nicaragua" },
  { code: "NER", country: "Níger" },
  { code: "NGA", country: "Nigeria" },
  { code: "NIU", country: "Niue" },
  { code: "NFK", country: "Isla Norfolk" },
  { code: "MNP", country: "Islas Marianas del Norte" },
  { code: "NOR", country: "Noruega" },
  { code: "OMN", country: "Omán" },
  { code: "PAK", country: "Pakistán" },
  { code: "PLW", country: "Palau" },
  { code: "PSE", country: "Palestina" },
  { code: "PAN", country: "Panamá" },
  { code: "PNG", country: "Papua Nueva Guinea" },
  { code: "PRY", country: "Paraguay" },
  { code: "PER", country: "Perú" },
  { code: "PHL", country: "Filipinas" },
  { code: "PCN", country: "Pitcairn" },
  { code: "POL", country: "Polonia" },
  { code: "PRT", country: "Portugal" },
  { code: "PRI", country: "Puerto Rico" },
  { code: "QAT", country: "Catar" },
  { code: "REU", country: "Reunión" },
  { code: "ROU", country: "Rumanía" },
  { code: "RUS", country: "Rusia" },
  { code: "RWA", country: "Ruanda" },
  { code: "SHN", country: "Santa Helena, Ascensión y Tristán de Acuña" },
  { code: "KNA", country: "Saint Kitts y Nevis" },
  { code: "LCA", country: "Santa Lucía" },
  { code: "SPM", country: "San Pedro y Miquelón" },
  { code: "VCT", country: "San Vicente y las Granadinas" },
  { code: "WSM", country: "Samoa" },
  { code: "SMR", country: "San Marino" },
  { code: "STP", country: "Santo Tomé y Príncipe" },
  { code: "SAU", country: "Arabia Saudita" },
  { code: "SEN", country: "Senegal" },
  { code: "SYC", country: "Seychelles" },
  { code: "SLE", country: "Sierra Leona" },
  { code: "SGP", country: "Singapur" },
  { code: "SVK", country: "Eslovaquia" },
  { code: "SVN", country: "Eslovenia" },
  { code: "SLB", country: "Islas Salomón" },
  { code: "SOM", country: "Somalia" },
  { code: "ZAF", country: "Sudáfrica" },
  { code: "SGS", country: "Georgia del Sur y las Islas Sandwich del Sur" },
  { code: "ESP", country: "España" },
  { code: "LKA", country: "Sri Lanka" },
  { code: "SDN", country: "Sudán" },
  { code: "SUR", country: "Suriname" },
  { code: "SJM", country: "Svalbard y Jan Mayen" },
  { code: "SWZ", country: "Esuatini" },
  { code: "SWE", country: "Suecia" },
  { code: "CHE", country: "Suiza" },
  { code: "SYR", country: "República Árabe Siria" },
  { code: "TWN", country: "Taiwán" },
  { code: "TJK", country: "Tayikistán" },
  { code: "TZA", country: "Tanzania" },
  { code: "THA", country: "Tailandia" },
  { code: "TLS", country: "Timor-Leste" },
  { code: "TGO", country: "Togo" },
  { code: "TKL", country: "Tokelau" },
  { code: "TON", country: "Tonga" },
  { code: "TTO", country: "Trinidad y Tobago" },
  { code: "TUN", country: "Túnez" },
  { code: "TUR", country: "Turquía" },
  { code: "TKM", country: "Turkmenistán" },
  { code: "TCA", country: "Islas Turcas y Caicos" },
  { code: "TUV", country: "Tuvalu" },
  { code: "UGA", country: "Uganda" },
  { code: "UKR", country: "Ucrania" },
  { code: "ARE", country: "Emiratos Árabes Unidos" },
  { code: "GBR", country: "Reino Unido" },
  { code: "USA", country: "Estados Unidos" },
  { code: "UMI", country: "Islas Ultramarinas Menores de los Estados Unidos" },
  { code: "URY", country: "Uruguay" },
  { code: "UZB", country: "Uzbekistán" },
  { code: "VUT", country: "Vanuatu" },
  { code: "VEN", country: "Venezuela" },
  { code: "VNM", country: "Vietnam" },
  { code: "VGB", country: "Islas Vírgenes británicas" },
  { code: "VIR", country: "Islas Vírgenes de los Estados Unidos" },
  { code: "WLF", country: "Wallis y Futuna" },
  { code: "ESH", country: "Sahara Occidental" },
  { code: "YEM", country: "Yemen" },
  { code: "ZMB", country: "Zambia" },
  { code: "ZWE", country: "Zimbabue" },
  { code: "ALA", country: "Islas Åland" },
  { code: "BES", country: "Bonaire, San Eustaquio y Saba" },
  { code: "CUW", country: "Curaçao" },
  { code: "GGY", country: "Guernsey" },
  { code: "IMN", country: "Isla de Man" },
  { code: "JEY", country: "Jersey" },
  { code: "MNE", country: "Montenegro" },
  { code: "BLM", country: "Saint Barthélemy" },
  { code: "MAF", country: "Saint Martin (francesa)" },
  { code: "SRB", country: "Serbia" },
  { code: "SXM", country: "Sint Maarten (neerlandesa)" },
  { code: "SSD", country: "Sudán del Sur" },
  { code: "XXK", country: "Kosovo" },
];
