export const countriesPT = [
  { code: "AFG", country: "Afeganistão" },
  { code: "ZAF", country: "África do Sul" },
  { code: "ALB", country: "Albânia" },
  { code: "DEU", country: "Alemanha" },
  { code: "AND", country: "Andorra" },
  { code: "AGO", country: "Angola" },
  { code: "AIA", country: "Anguila" },
  { code: "ATA", country: "Antártida" },
  { code: "ATG", country: "Antígua e Barbuda" },
  { code: "SAU", country: "Arábia Saudita" },
  { code: "DZA", country: "Argélia" },
  { code: "ARG", country: "Argentina" },
  { code: "ARM", country: "Arménia" },
  { code: "ABW", country: "Aruba" },
  { code: "AUS", country: "Austrália" },
  { code: "AUT", country: "Áustria" },
  { code: "AZE", country: "Azerbaijão" },
  { code: "BHS", country: "Bahamas" },
  { code: "BHR", country: "Bahrein" },
  { code: "BGD", country: "Bangladesh" },
  { code: "BRB", country: "Barbados" },
  { code: "BEL", country: "Bélgica" },
  { code: "BLZ", country: "Belize" },
  { code: "BEN", country: "Benim" },
  { code: "BMU", country: "Bermudas" },
  { code: "BLR", country: "Bielorrússia" },
  { code: "BOL", country: "Bolívia" },
  { code: "BIH", country: "Bósnia-Herzegovina" },
  { code: "BWA", country: "Botsuana" },
  { code: "BRA", country: "Brasil" },
  { code: "BRN", country: "Brunei" },
  { code: "BGR", country: "Bulgária" },
  { code: "BFA", country: "Burkina Faso" },
  { code: "BDI", country: "Burundi" },
  { code: "BTN", country: "Butão" },
  { code: "CPV", country: "Cabo Verde" },
  { code: "KHM", country: "Camboja" },
  { code: "CAN", country: "Canadá" },
  { code: "QAT", country: "Qatar" },
  { code: "KAZ", country: "Cazaquistão" },
  { code: "TCD", country: "Chade" },
  { code: "CHL", country: "Chile" },
  { code: "CHN", country: "China" },
  { code: "CYP", country: "Chipre" },
  { code: "VAT", country: "Santa Sé" },
  { code: "SGP", country: "Singapura" },
  { code: "COL", country: "Colômbia" },
  { code: "COM", country: "Comores" },
  { code: "COG", country: "República Democrática do Congo" },
  { code: "COD", country: "República Popular do Congo" },
  { code: "PRK", country: "Coreia do Norte" },
  { code: "KOR", country: "Coreia do Sul" },
  { code: "CIV", country: "Costa do Marfim" },
  { code: "CRI", country: "Costa Rica" },
  { code: "HRV", country: "Croácia" },
  { code: "CUB", country: "Cuba" },
  { code: "CUW", country: "Curaçao" },
  { code: "DNK", country: "Dinamarca" },
  { code: "DJI", country: "Djibouti" },
  { code: "DMA", country: "Dominica" },
  { code: "EGY", country: "Egito" },
  { code: "SLV", country: "El Salvador" },
  { code: "ARE", country: "Emirados Árabes Unidos" },
  { code: "ECU", country: "Equador" },
  { code: "ERI", country: "Eritreia" },
  { code: "SVK", country: "Eslováquia" },
  { code: "SVN", country: "Eslovénia" },
  { code: "ESP", country: "Espanha" },
  { code: "USA", country: "Estados Unidos" },
  { code: "EST", country: "Estónia" },
  { code: "ETH", country: "Etiópia" },
  { code: "FJI", country: "Fiji" },
  { code: "PHL", country: "Filipinas" },
  { code: "FIN", country: "Finlândia" },
  { code: "FRA", country: "França" },
  { code: "GAB", country: "Gabão" },
  { code: "GMB", country: "Gâmbia" },
  { code: "GHA", country: "Gana" },
  { code: "GEO", country: "Geórgia" },
  { code: "SGS", country: "Geórgia do Sul e Ilhas Sandwich do Sul" },
  { code: "GIB", country: "Gibraltar" },
  { code: "GRD", country: "Granada" },
  { code: "GRC", country: "Grécia" },
  { code: "GRL", country: "Gronelândia" },
  { code: "GLP", country: "Guadalupe" },
  { code: "GUM", country: "Guam" },
  { code: "GTM", country: "Guatemala" },
  { code: "GGY", country: "Guernsey" },
  { code: "GUY", country: "Guiana" },
  { code: "GUF", country: "Guiana Francesa" },
  { code: "GIN", country: "Guiné" },
  { code: "GNB", country: "Guiné-Bissau" },
  { code: "GNQ", country: "Guiné Equatorial" },
  { code: "HTI", country: "Haiti" },
  { code: "NLD", country: "Países Baixos" },
  { code: "HND", country: "Honduras" },
  { code: "HKG", country: "Hong Kong" },
  { code: "HUN", country: "Hungria" },
  { code: "YEM", country: "Iémen" },
  { code: "BVT", country: "Ilha Bouvet" },
  { code: "CXR", country: "Ilha de Natal" },
  { code: "IMN", country: "Ilha de Man" },
  { code: "NFK", country: "Ilha Norfolk" },
  { code: "ALA", country: "Ilhas Åland" },
  { code: "CYM", country: "Ilhas Caimão" },
  { code: "CCK", country: "Ilhas Cocos (Keeling)" },
  { code: "COK", country: "Ilhas Cook" },
  { code: "UMI", country: "Ilhas Distantes dos EUA" },
  { code: "HMD", country: "Ilha Heard e Ilhas McDonald" },
  { code: "FRO", country: "Ilhas Faroé" },
  { code: "FLK", country: "Ilhas Malvinas" },
  { code: "MNP", country: "Ilhas Marianas do Norte" },
  { code: "MHL", country: "Ilhas Marshall" },
  { code: "PCN", country: "Ilhas Pitcairn" },
  { code: "SLB", country: "Ilhas Salomão" },
  { code: "TCA", country: "Ilhas Turcas e Caicos" },
  { code: "VGB", country: "Ilhas Virgens Britânicas" },
  { code: "VIR", country: "Ilhas Virgens Americanas" },
  { code: "IND", country: "Índia" },
  { code: "IDN", country: "Indonésia" },
  { code: "IRN", country: "Irão" },
  { code: "IRQ", country: "Iraque" },
  { code: "IRL", country: "Irlanda" },
  { code: "ISL", country: "Islândia" },
  { code: "ISR", country: "Israel" },
  { code: "ITA", country: "Itália" },
  { code: "JAM", country: "Jamaica" },
  { code: "JPN", country: "Japão" },
  { code: "JEY", country: "Jersey" },
  { code: "JOR", country: "Jordânia" },
  { code: "KWT", country: "Koweit" },
  { code: "LAO", country: "Laos" },
  { code: "LSO", country: "Lesoto" },
  { code: "LVA", country: "Letónia" },
  { code: "LBN", country: "Líbano" },
  { code: "LBR", country: "Libéria" },
  { code: "LBY", country: "Líbia" },
  { code: "LIE", country: "Liechtenstein" },
  { code: "LTU", country: "Lituânia" },
  { code: "LUX", country: "Luxemburgo" },
  { code: "MAC", country: "Macau" },
  { code: "MKD", country: "Macedónia do Norte" },
  { code: "MDG", country: "Madagáscar" },
  { code: "MYS", country: "Malásia" },
  { code: "MWI", country: "Maláui" },
  { code: "MDV", country: "Maldivas" },
  { code: "MLI", country: "Mali" },
  { code: "MLT", country: "Malta" },
  { code: "MAR", country: "Marrocos" },
  { code: "MTQ", country: "Martinica" },
  { code: "MUS", country: "Maurícia" },
  { code: "MRT", country: "Mauritânia" },
  { code: "MYT", country: "Mayotte" },
  { code: "MEX", country: "México" },
  { code: "MMR", country: "Mianmar (Birmânia)" },
  { code: "FSM", country: "Micronésia" },
  { code: "MOZ", country: "Moçambique" },
  { code: "MDA", country: "Moldávia" },
  { code: "MCO", country: "Mónaco" },
  { code: "MNG", country: "Mongólia" },
  { code: "MNE", country: "Montenegro" },
  { code: "MSR", country: "Monserrate" },
  { code: "NAM", country: "Namíbia" },
  { code: "NRU", country: "Nauru" },
  { code: "NPL", country: "Nepal" },
  { code: "NIC", country: "Nicarágua" },
  { code: "NER", country: "Níger" },
  { code: "NGA", country: "Nigéria" },
  { code: "NIU", country: "Niue" },
  { code: "NOR", country: "Noruega" },
  { code: "NCL", country: "Nova Caledónia" },
  { code: "NZL", country: "Nova Zelândia" },
  { code: "OMN", country: "Omã" },
  { code: "BES", country: "Países Baixos Caribenhos" },
  { code: "PLW", country: "Palau" },
  { code: "PAN", country: "Panamá" },
  { code: "PNG", country: "Papua-Nova Guiné" },
  { code: "PAK", country: "Paquistão" },
  { code: "PRY", country: "Paraguai" },
  { code: "PER", country: "Peru" },
  { code: "PYF", country: "Polinésia Francesa" },
  { code: "POL", country: "Polónia" },
  { code: "PRI", country: "Porto Rico" },
  { code: "PRT", country: "Portugal" },
  { code: "KEN", country: "Quénia" },
  { code: "KGZ", country: "Quirguistão" },
  { code: "KIR", country: "Quiribati" },
  { code: "GBR", country: "Reino Unido" },
  { code: "CAF", country: "República Centro-Africana" },
  { code: "DOM", country: "República Dominicana" },
  { code: "CMR", country: "Camarões" },
  { code: "CZE", country: "Chéquia" },
  { code: "REU", country: "Reunião" },
  { code: "ROU", country: "Roménia" },
  { code: "RWA", country: "Ruanda" },
  { code: "RUS", country: "Rússia" },
  { code: "ESH", country: "Saara Ocidental" },
  { code: "SPM", country: "Saint Pierre e Miquelon" },
  { code: "WSM", country: "Samoa" },
  { code: "ASM", country: "Samoa Americana" },
  { code: "SMR", country: "San Marino" },
  { code: "SHN", country: "Santa Helena" },
  { code: "LCA", country: "Santa Lúcia" },
  { code: "BLM", country: "São Bartolomeu" },
  { code: "KNA", country: "São Cristóvão e Neves" },
  { code: "MAF", country: "São Martinho" },
  { code: "STP", country: "São Tomé e Príncipe" },
  { code: "VCT", country: "São Vicente e Granadinas" },
  { code: "SEN", country: "Senegal" },
  { code: "SLE", country: "Serra Leoa" },
  { code: "SRB", country: "Sérvia" },
  { code: "SYC", country: "Seychelles" },
  { code: "SXM", country: "São Martinho" },
  { code: "SYR", country: "Síria" },
  { code: "SOM", country: "Somália" },
  { code: "LKA", country: "Sri Lanka" },
  { code: "SWZ", country: "Essuatíni" },
  { code: "SDN", country: "Sudão" },
  { code: "SSD", country: "Sudão do Sul" },
  { code: "SWE", country: "Suécia" },
  { code: "CHE", country: "Suíça" },
  { code: "SUR", country: "Suriname" },
  { code: "SJM", country: "Svalbard e Jan Mayen" },
  { code: "THA", country: "Tailândia" },
  { code: "TWN", country: "Taiwan" },
  { code: "TJK", country: "Tajiquistão" },
  { code: "TZA", country: "Tanzânia" },
  { code: "IOT", country: "Território Britânico do Oceano Índico" },
  { code: "ATF", country: "Terras Austrais e Antárticas Francesas" },
  { code: "PSE", country: "Territórios palestinos" },
  { code: "TLS", country: "Timor-Leste" },
  { code: "TGO", country: "Togo" },
  { code: "TKL", country: "Tokelau" },
  { code: "TON", country: "Tonga" },
  { code: "TTO", country: "Trindade e Tobago" },
  { code: "TUN", country: "Tunísia" },
  { code: "TKM", country: "Turquemenistão" },
  { code: "TUR", country: "Turquia" },
  { code: "TUV", country: "Tuvalu" },
  { code: "UKR", country: "Ucrânia" },
  { code: "UGA", country: "Uganda" },
  { code: "URY", country: "Uruguai" },
  { code: "UZB", country: "Uzbequistão" },
  { code: "VUT", country: "Vanuatu" },
  { code: "VEN", country: "Venezuela" },
  { code: "VNM", country: "Vietname" },
  { code: "WLF", country: "Wallis e Futuna" },
  { code: "ZMB", country: "Zâmbia" },
  { code: "ZWE", country: "Zimbábue" },
  { code: "XXK", country: "Kosovo" },
];
